config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :categories, only: :index do
    resources :lessons
  end
  resources :relationships
  resources :words
  namespace :admin  do
    root "static_pages#home"
    resources :users
    resources :categories
    resources :words
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy

  validates :content, presence: true, length: {maximum: 100}
  validate :validate_answers

  accepts_nested_attributes_for :answers, allow_destroy: true

  scope :search, ->keyword {where "content LIKE ?", "%#{keyword}%"}

  scope :random_words, -> {order("RANDOM()")}

  QUERY_LEARNED = "content like :search and id in (select word_id
    FROM results r INNER JOIN lessons l
    ON r.lesson_id = l.id AND l.user_id = :user_id)"
  QUERY_NOT_LEARNED = "content like :search and id not in (select word_id
    FROM results r INNER JOIN lessons l
    ON r.lesson_id = l.id AND l.user_id = :user_id)"

  scope :learned, -> user_id, search{
    where QUERY_LEARNED, user_id: user_id, search: "%#{search}%"
  }
  scope :not_learned, -> user_id, search{
    where QUERY_NOT_LEARNED, user_id: user_id, search: "%#{search}%"
  }
  scope :filter_category, -> category_id{
    where "category_id = ?", "#{category_id}"
  }
  scope :show_all, -> user_id, keyword{
    where("content LIKE ? ", "%#{keyword}%")
  }
  def validate_answers
    if answers.size < Settings.minimum_answer
      errors.add :answers, I18n.t("answer_must_more_one")
    end
    if answers.reject{|answer| !answer.is_correct?}.count == 0
      errors.add :answers, I18n.t("word_must_has_correct_answer")
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :load_word, only: [:destroy, :edit, :update]

  def index
    if params[:key]
      @words = Word.includes(:category).search params[:key]
      respond_to do |format|
        format.json do
          render json: @words
        end
      end
    elsif params[:search]
      @words = Word.includes(:category).search params[:search].paginate page: params[:page],
        per_page: Settings.per_page
    else
      @words = Word.includes(:category).paginate page: params[:page],
        per_page: Settings.per_page
      @word = Word.new
      @word.answers.new
      @categories = Category.all
    end
  end

  def new
  end

  def create
    @word = Word.create word_params
    if @word.save
      respond_to do |format|
        format.html do
          flash[:success] = t "create_success"
          redirect_to admin_words_path
        end
        format.json do
          render json: @word
        end
      end
    else
      flash[:danger] = t "create_failed"
      redirect_to admin_words_path
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t "update_success"
      redirect_to admin_words_path
    else
      flash[:danger] = t "update_failed"
    end
  end

  def destroy
    if @word.destroy
      respond_to do |format|
        format.json do
          render json: {status: @word.destroyed?}
        end
      end
    else
      flash[:danger] = t "delete_failed"
      redirect_to admin_words_path
    end
  end

  private

  def load_word
    @word = Word.find_by id: params[:id]
    unless @word
      flash[:danger] = t "word_not_exist"
      redirect_to admin_words_path
    end
  end

  def word_params
    params.require(:word).permit :content, :category_id,
      answers_attributes: [:id, :content, :is_correct]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user
  def index
    @categories = Category.all
    if params[:category_id] && params[:word_filter] && params[:word_search]
      @words = Word.includes(:answers).filter_category(params[:category_id])
        .send(params[:word_filter], current_user.id, params[:word_search])
        .paginate page: params[:page], per_page: Settings.per_page
    else
      @words = Word.includes(:answers)
        .paginate page: params[:page], per_page: Settings.per_page
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/words/_answer_fields.html.erb
<div class="form-group choice_question">
  <div class="col-md-12">
    <div class="col-md-8">
      <%= f.label t ".answer_name" %>
      <%= f.text_field :content, class: "form-control" %>
    </div>
    <div class="col-md-3 space-top-remove">
      <%= f.label t ".is_correct" %>
      <%= f.check_box :is_correct, class: "answers_checkbox" %><br>
    </div>
    <div class="col-md-1 space-top-remove">
      <%= link_to_remove_fields t("remove_answer"), f %>
    </div>
  </div>
</div>

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word], remote: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="modal-body">
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :category %>
      <%= f.select "category_id", options_for_select(@categories.collect{
        |category| [category.name, category.id]}),
        class: "btn btn-default filter-categories" %>
    </div>
    <%= f.fields_for :answers do |answer_builder| %>
      <%= render "answer_fields", f: answer_builder %>
    <% end %>
    <div class="add_fields">
      <%= link_to_add_fields t("add_answer"), f, :answers %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit yield(:button_text), class: "btn btn-primary", id: "btn-submit" %>
  </div>
<% end %>

app/views/admin/words/_new.html.erb
<% provide :button_text, t(".add") %>
<div class="modal fade new-word-modal" tabindex="-1" role="dialog"
  aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
          aria-hidden="true">&times;</button>
        <h4 class="modal-title text-center"><%= t "new_word" %></h4>
      </div>
        <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/words/edit.html.erb
<% provide :button_text, t(".update") %>
<div class="row box">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= t "edit_word" %></h1>
    <%= render "form" %>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide :title, (t ".allword") %>
<h1><%= t ".allword" %></h1>
<%= form_tag admin_words_path, method: :get do %>
  <div class="form-group row">
    <div class="col-xs-8">
      <div class="search">
        <h4><%= t ".search" %></h4>
      </div>
    </div>
    <div class="col-xs-4">
      <%= text_field_tag :word_search, params[:search], class: "form-control" %>
    </div>
  </div>
<% end %>
<div>
  <button type="button" class="btn btn-primary" data-toggle="modal"
    data-target=".new-word-modal"><%= t "new" %></button>
</div>
</br>
<table class="table table-hover bg-table ls-users">
  <thead class="title_table">
    <tr>
      <th class="text-c"><%= t ".content" %></th>
      <th class="text-c"><%= t ".category" %></th>
      <th class="text-c"><%= t ".edit" %></th>
      <th class="text-c"><%= t ".delete" %></th>
    </tr>
  </thead>
  <tbody id ="result_search">
    <% @words.each.with_index do |word| %>
      <tr id="word-<%= word.id %>">
        <td class="text-c"><%= word.content %></td>
        <td class="text-c"><%= word.category.name %></td>
        <td>
          <%= link_to t("edit"), edit_admin_word_path(word.id),
            class: "btn btn-default glyphicon glyphicon-pencil" %>
        </td>
        <td class="text-c">
          <button class = "danger btn btn-default glyphicon glyphicon-trash
            delete-category" onclick = "delWord(<%= word.id %>)">
            <%= t ".delete" %>
          </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>
<%= render "new" %>