config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :categories, only: :index do
    resources :lessons
  end
  resources :relationships
  resources :words
  namespace :admin  do
    root "static_pages#home"
    resources :users
    resources :categories
    resources :words
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :activitys, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}

  enum role: [:user, :admin]

  has_secure_password

  before_save {self.email = email.downcase}

  scope :search, ->keyword { where "name LIKE ?", "%#{keyword}%" }

  def is_user? user
    self == user
  end

  def feed
    Activity.where("user_id IN (?) OR user_id = ?", following_ids, id)
  end

  def follow other_user
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include?(other_user)
  end

  def create_activity action_type, target_id
    self.activitys.build(user_id: self.id, target_id: target_id,
      action_type: action_type).save
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user, only: :index
  before_action :load_user, only: [:destroy, :show]
  before_action :verify_admin, only: :index

  def index
    if params[:key]
      @users = User.user.search params[:key]
      respond_to do |format|
        format.json do
          render json: @users
        end
      end
    elsif params[:search]
      @users = User.user.search(params[:search]).
        paginate page: params[:page],
        per_page: Settings.per_page
    else
      @users = User.user.paginate page: params[:page],
        per_page: Settings.per_page
    end
  end

  def show

  end

  def destroy
    respond_to do |format|
      if @user.destroy
        format.json do
          render json: {status: t("delete_success")}
        end
      else
        format.json do
          render json: {status: t("delete_failed")}
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :load_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.user.search(params[:search_users]).
      paginate page: params[:page],
      per_page: Settings.per_page
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t "register_success"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "update_success"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end
end

app/views/admin/users/index.html.erb
<% provide :title, (t ".alluser") %>
<h1><%= t ".alluser" %></h1>
<%= form_tag admin_users_path, method: :get do %>
  <div class="form-group row">
    <div class="col-xs-8">
      <div class="search">
        <h4><%= t ".search" %></h4>
      </div>
    </div>
    <div class="col-xs-4">
      <%= text_field_tag :user_search, params[:search], class: "form-control" %>
    </div>
  </div>
<% end %>
<table class="table table-hover bg-table ls-users">
  <thead class="title_table">
    <tr>
      <th class="text-c"><%= t ".avatar" %></th>
      <th class="text-c"><%= t ".name" %></th>
      <th class="text-c"><%= t ".email" %></th>
    </tr>
  </thead>
  <tbody id ="result_search">
    <% @users.each.with_index do |user| %>
      <tr id="user-<%= user.id %>">
        <input type="hidden" value = "<%= user.id%>">
        <td class="text-c">
          <%= image_tag "user_icon.png", class: "avatar" %>
        </td>
        <td class="text-c"><%= link_to user.name, user %></td>
        <td class="text-c"><%= user.email %></td>
        <td class="text-c">
          <button class = "glyphicon glyphicon-trash
            text-danger delete-user" onclick = "del(<%= user.id %>)">
            <%= t ".delete" %>
          </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>